#!/bin/sh

#cleanup
rm -rf obj_dir
rm -f cpu1.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall -cc --trace cpu1.sv --exe cpu1_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vcpu1.mk Vcpu1

# run executable simulation file
obj_dir/Vcpu1