#!/bin/sh

#cleanup
rm -rf obj_dir
rm -f top.vcd

<<<<<<< HEAD
# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall -cc --trace top.sv --exe top_tb.cpp
=======
verilator -Wall -cc --trace top.sv --exe testbench.cpp -Irtl -Itest
>>>>>>> v2.0-Pipeline

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vtop.mk Vtop

# run executable simulation file
obj_dir/Vtop
