#!/bin/sh

#cleanup
rm -rf obj_dir
rm -f two_way_set_associative_cache.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall -cc --trace two_way_set_associative_cache.sv --exe two_way_set_associative_cache_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vtwo_way_set_associative_cache.mk Vtwo_way_set_associative_cache

# run executable simulation file
obj_dir/Vtwo_way_set_associative_cache