#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f DataMemory.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace DataMemory.sv --exe DataMemory_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f VDataMemory.mk VDataMemory

# run executable simulation file
obj_dir/VDataMemory
