#!/bin/sh

#cleanup
rm -rf obj_dir
rm -f rom.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall -cc --trace rom.sv --exe rom_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vrom.mk Vrom

# run executable simulation file
obj_dir/Vrom