#!/bin/sh

#cleanup
rm -rf obj_dir
rm -f test.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall -cc --trace test.sv --exe test_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vtest.mk Vtest

# run executable simulation file
obj_dir/Vtest